name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "Test User"

      - name: Run tests
        run: make test

      - name: Test installation
        run: |
          sudo make install PREFIX=/usr/local
          which wt
          wt help

      - name: Test shell completions
        run: |
          # Test bash completion
          bash -c "source /usr/local/share/wt/completions/wt.bash && complete -p wt"

      - name: Test worktree creation
        run: |
          mkdir test-repo
          cd test-repo
          git init -b main
          echo "test" > README.md
          git add README.md
          git commit -m "Initial commit"
          wt feature-test -n
          [ -d "../test-repo-worktrees/feature-test" ]

  # shellcheck:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Run ShellCheck
  #     uses: ludeeus/action-shellcheck@master
  #     with:
  #       check_together: 'yes'
  #       ignore_paths: 'completions/wt.zsh'

  release:
    needs: [test]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v3

      - name: Create release package
        run: make release

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/wt-*.tar.gz
          asset_name: wt-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
