name: Release and Update Homebrew

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create tarball
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          # Create a directory with version name
          mkdir -p wt-${VERSION#v}
          
          # Copy all necessary files
          cp -r bin completions docs README.md LICENSE .wtconfig.example wt-${VERSION#v}/
          
          # Create tarball
          tar -czf ${GITHUB_WORKSPACE}/wt-${VERSION#v}.tar.gz wt-${VERSION#v}
          
          # Calculate SHA256
          SHA256=$(sha256sum wt-${VERSION#v}.tar.gz | awk '{print $1}')
          echo "SHA256=${SHA256}" >> $GITHUB_ENV
          echo "TARBALL=wt-${VERSION#v}.tar.gz" >> $GITHUB_ENV

      - name: Generate changelog
        id: changelog
        run: |
          # Get previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          
          {
            echo "## What's Changed"
            echo ""
            if [ -n "$PREV_TAG" ]; then
              git log --pretty=format:"* %s by @%an in %h" $PREV_TAG..HEAD | grep -v "Merge pull request"
            else
              echo "* Initial release"
            fi
            echo ""
            echo "**Full Changelog**: https://github.com/${{ github.repository }}/compare/${PREV_TAG}...${{ steps.get_version.outputs.VERSION }}"
          } > CHANGELOG.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.TARBALL }}
          body_path: CHANGELOG.md
          name: wt ${{ steps.get_version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout clean copy for formula update
        uses: actions/checkout@v4
        with:
          path: formula-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Homebrew Formula
        working-directory: formula-repo
        run: |
          # Setup git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Update formula
          VERSION=${{ steps.get_version.outputs.VERSION }}
          VERSION_NUM=${VERSION#v}
          
          # Update the formula file
          sed -i.bak -e "s|url \".*\"|url \"https://github.com/${{ github.repository }}/releases/download/${VERSION}/wt-${VERSION_NUM}.tar.gz\"|" \
                     -e "s|sha256 \".*\"|sha256 \"${{ env.SHA256 }}\"|" \
                     Formula/wt.rb
          
          # Remove backup file
          rm -f Formula/wt.rb.bak

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: formula-repo
          branch: formula-update-${{ steps.get_version.outputs.VERSION }}
          commit-message: "formula: update to ${{ steps.get_version.outputs.VERSION }}"
          title: "formula: update to ${{ steps.get_version.outputs.VERSION }}"
          body: |
            Updates the Homebrew formula to ${{ steps.get_version.outputs.VERSION }}.
            
            - SHA256: `${{ env.SHA256 }}`
            - Release: https://github.com/${{ github.repository }}/releases/tag/${{ steps.get_version.outputs.VERSION }}
            
            To install this version:
            ```bash
            brew update
            brew upgrade wt
            ```
          assignees: thekniru
          labels: homebrew, automated